In [3]:
import numpy as np
a = np.random.randn(5)
print(a)

[-2.29798167  0.63231539 -0.47975587  0.0869856   1.17374798]


In [7]:
print(a.shape)

(5,)
[-2.29798167  0.63231539 -0.47975587  0.0869856   1.17374798]
7.295959036506625


In [8]:
print(a.T) # print a transpose

[-2.29798167  0.63231539 -0.47975587  0.0869856   1.17374798]


In [9]:
print(np.dot(a, a.T)) # this dot product will produce a number instead of a matrix.

7.295959036506625


(5,) is called a "rank 1 array" & usually known in Data Structures. This method is not recommended to use in Neural Network computation since it is inconsistent. Instead, use the method below.

In [12]:
a = np.random.randn(5,1) # specify the column vector
print(a)

[[-0.40194274]
 [-1.0281759 ]
 [ 0.18444534]
 [ 0.45678446]
 [ 1.44136207]]


In [18]:
assert(a.shape == (5,1)) # make sure that our matrix is 5,1
a = a.reshape((5,1)) # tips from Andrew: don't be shy about recalling the reshape() function to make sure about our matrix dimension.

In [13]:
print(a.T)

[[-0.40194274 -1.0281759   0.18444534  0.45678446  1.44136207]]


In [14]:
print(np.dot(a, a.T)) # this dot product will produce a matrix! :D

[[ 0.16155797  0.41326784 -0.07413646 -0.1836012  -0.57934502]
 [ 0.41326784  1.05714568 -0.18964225 -0.46965477 -1.48197374]
 [-0.07413646 -0.18964225  0.03402008  0.08425176  0.26585251]
 [-0.1836012  -0.46965477  0.08425176  0.20865204  0.65839179]
 [-0.57934502 -1.48197374  0.26585251  0.65839179  2.07752461]]
